POST http://localhost:8000/user-service/users
Content-Type: application/json

{
    "email": "seol@naver.com",
    "name": "seol",
    "pwd": "test1234"
}

###
POST http://localhost:8000/user-service/login
Content-Type: application/json

{
    "email": "seol@naver.com",
    "password": "test1234"
}

###
GET http://localhost:8000/user-service/users/af6c78bc-d444-4129-83be-d87fb3229d18
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZjZjNzhiYy1kNDQ0LTQxMjktODNiZS1kODdmYjMyMjlkMTgiLCJleHAiOjE2NjA5OTc2ODl9.NgPSg4F47JS2EoxNi8ax4hlVR96R2wxmwdqnhIVJymjEZ7WnOwRIa9ZOJGs_Udsnz2xLCvN8BQNiz1egfeERzQ

###
GET http://localhost:8000/order-service/health_check

###
GET http://localhost:8000/catalog-service/catalogs

###
POST http://localhost:8000/order-service/af6c78bc-d444-4129-83be-d87fb3229d18/orders
Content-Type: application/json

{
    "productId": "catalog-0002",
    "qty": 50,
    "unitPrice": 900
}
###
GET http://localhost:8000/order-service/af6c78bc-d444-4129-83be-d87fb3229d18/orders


###
POST http://localhost:8000/study-service/