POST http://localhost:8000/user-service/users
Content-Type: application/json

{
    "email": "seol@naver.com",
    "name": "seol",
    "pwd": "test1234"
}

###
POST http://localhost:8000/user-service/login
Content-Type: application/json

{
    "email": "seol@naver.com",
    "password": "test1234"
}

###
GET http://localhost:8000/user-service/users/bf0d0b68-eb4f-4830-9ea7-9697a0a64d6f
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJiZjBkMGI2OC1lYjRmLTQ4MzAtOWVhNy05Njk3YTBhNjRkNmYiLCJleHAiOjE2NjEwODczNTB9.IMfhIOjfjonCA3-DLURGM72fp7dUL0dHDdwFUyoJAXf015NX7QSvL1Mdr4ZPK0BMiS1c1eHckrkfB10ZJLwxMA

###
GET http://localhost:8000/order-service/health_check

###
GET http://localhost:8000/catalog-service/catalogs

###
POST http://localhost:8000/order-service/10193548-79c8-4793-9933-823416225100/orders
Content-Type: application/json

{
    "productId": "catalog-0002",
    "qty": 20,
    "unitPrice": 900
}
###
GET http://localhost:8000/order-service/bf0d0b68-eb4f-4830-9ea7-9697a0a64d6f/orders


###
POST http://localhost:8000/study-service/