POST http://localhost:8000/user-service/users
Content-Type: application/json

{
    "email": "seol@naver.com",
    "name": "seol",
    "pwd": "test1234"
}

###
POST http://localhost:8000/user-service/login
Content-Type: application/json

{
    "email": "seol@naver.com",
    "password": "test1234"
}

###
GET http://localhost:8000/user-service/users/194dced3-629d-4a2e-9cab-b81ea8636d36
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyNDliMWVjMC01MDY2LTQ5N2YtYWU3Ny1hYzNkM2VkMTVjOWYiLCJleHAiOjE2NjAwMzQxNDR9.jbaV0cPVL5HWvQu3qK34s-6F31oJIvWjjL4NvQebN6OPFjBSVA6ucRzuN3_14JeCxAWr5ccTQCYs5aIpzEgv8Q

###
GET http://localhost:8000/order-service/health_check
###
POST http://localhost:8000/order-service/194dced3-629d-4a2e-9cab-b81ea8636d36/orders
Content-Type: application/json

{
    "productId": "PRO_14",
    "qty": 50,
    "unitPrice": 20000
}
###
GET http://localhost:8000/order-service/194dced3-629d-4a2e-9cab-b81ea8636d36/orders


###
POST http://localhost:8000/study-service/